name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Defines which part of a SemVer should be increased during the release process, e.g "major", "minor" or "patch".'
        default: 'minor'
      preRelease:
        description: 'Defines whether a release is final or a pre-release for internal testing, e.g "beta", "alpha" or "rc".'


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Linux Dependencies
        run: sudo apt-get install libgconf-2-4

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit Test
        run: npm run test

      - name: E2E Test
        run: npm run e2e

      - name: Install release-it
        run: npm install -g release-it@13.7.1

      - name: Release
        run: |
          release-it \
            --increment='${{ github.event.inputs.increment }}' \
            --preRelease='${{ github.event.inputs.preRelease }}' \
            --ci
